[package]
name = "bugsyth_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = "0.36.0"
image = "0.25.5"
obj = "0.10.2"
vek = "0.17.1"
cpal = "0.15.3"
rand = "0.9.0"

[dev-dependencies]
bugsyth_engine_imgui_support = "0.3.1"